Check GPUController is started before getting GPU info
BartoszCichecki/LenovoLegionToolkit pull request #1502
Opened 2024-11-26 18:23 UTC by Ace-Radom

Closes: #1501.

Add a `Started` state to `GPUController`. Check the state before getting GPU info to make sure datas would be got successfully.

2024-11-26 22:14 UTC, BartoszCichecki requested changes

2024-11-27 10:09 UTC, Ace-Radom commented on LenovoLegionToolkit.Lib/Controllers/Sensors/AbstractSensorsController.cs
> +        if (gpuController.IsSupported() && !gpuController.Started)
Is the `IsSupported` check also unnecessary? Currently in `StartAsync` there's no compatibility check and `GPUController` doesn't work for AMD GPUs.

2024-11-27 10:15 UTC, Ace-Radom commented on LenovoLegionToolkit.Lib/Controllers/GPUController.cs
> +        Started = true;
Indeed, and with the removement of `await StopAsync(true).ConfigureAwait(false);` `StartAsync` doesn't use any async method any more. Should I rename it into a normal sync method like `private void Start(int delay, int interval)` or should I keep it as an async method?

2024-11-27 11:45 UTC, Ace-Radom commented on LenovoLegionToolkit.Lib/Controllers/GPUController.cs
> +        Started = true;
Nah I'll just return a CompletedTask for now...so much changes would be too complicated.

2025-01-01 19:18 UTC, BartoszCichecki approved these changes

2025-01-01 19:18 UTC, merged