Added day of the week based automation.
BartoszCichecki/LenovoLegionToolkit pull request #736
Opened 2023-05-24 19:42 UTC by Ekscentricitet

Added day of the week based automation based on the existing code. Introduced a new struct Day and used it to transfer information from the listener to the pipeline trigger. Added subtitles for when this automation is chosen. The day of the week is localized, which might be a problem if, for example, the language of the OS is Bulgarian but the program is in English. Another approach would be to read the week from the resources but then we will have to add the 7 days of the week as a translation task for all languages.

2023-05-24 19:48 UTC, Ekscentricitet commented
It seems like there are some changes that I did not make. I will investigate how they landed in the pull request and revert them.

2023-05-24 19:49 UTC, BartoszCichecki commented
You most likely need to pull latest changes from my repo. I think GH allows you to sync with upstream repo.

2023-05-24 20:01 UTC, Ekscentricitet commented
Alright, now there should be only my changes.

2023-05-25 15:11 UTC, BartoszCichecki requested changes
Good job, couple comments only: localization and cleaning up of the day/time situation. It's a little bit weird that Day also contains time and in many places both are used.

2023-05-25 20:14 UTC, Ekscentricitet commented on LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/IAutomationPipelineTrigger.cs
> +    Day? Day { get; }
How do you propose to implement it? Should `Day` be removed as a struct and `DayOfWeek` be used instead? Then the `TimeAutomationEvent` would contain a `DateTime` object, while the `TimeAutomationPipelineTrigger` would have a `List<DayOfWeek> days` parameter. The Form will be passing both `Time` and `List<DayOfWeek>` when day automation is selected. And some checklist added to the UI.

2023-05-25 20:14 UTC, Ekscentricitet commented on LenovoLegionToolkit.WPF/Windows/Automation/TabItemContent/TimeAutomationPipelineTriggerTabItemContent.xaml
> +                <ComboBoxItem Content="Monday" />
I localized the subtitles but didn't pay attention to these. Good catch!

2023-05-25 21:27 UTC, BartoszCichecki commented on LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/IAutomationPipelineTrigger.cs
> +    Day? Day { get; }
I think that we can just store `DayOfWeek[]` just make sure that it's serialized and deserialized correctly. `TimeAutomationEvent` Can have two properties, you can just add `DayOfWeek[]` to the existing `Time` property.

```
public readonly struct TimeAutomationEvent : IAutomationEvent
{
    public Time Time { get; init; }
    public DayOfWeek[] Days { get; init; }
}
```

2023-05-25 21:30 UTC, BartoszCichecki commented on LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/IAutomationPipelineTrigger.cs
> +    Day? Day { get; }
Also, in `TimeAutomationListener` you can change the event to use a tuple:

`public event EventHandler<(Time, DayOfWeek[])>? Changed;`

This way we can easily pass the DayOfWeek together with time. I would assume that if the array is empty, event will apply to all days.

2023-05-25 21:33 UTC, BartoszCichecki commented on LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/IAutomationPipelineTrigger.cs
> +    Day? Day { get; }
I assume you know about tuple deconstruction? They are pretty cool to use. You can do

`var tuple = ("string", 1)`

and later you can deconstruct it:

`var (text, number) = tuple`.

Just a hint ;)

2023-05-26 19:51 UTC, Ekscentricitet commented on LenovoLegionToolkit.Lib.Automation/Pipeline/Triggers/IAutomationPipelineTrigger.cs
> +    Day? Day { get; }
I haven't worked with Touples much. I am not sure if they make a big difference here, but I used them for practice. Let me know if I did something incorrectly.

2023-05-27 09:55 UTC, BartoszCichecki approved these changes

2023-05-28 15:19 UTC, merged

2025-02-26 23:27 UTC, ZupoLlask commented
Hi!

It seems this is what I was looking for: combine certain triggers with a specific day of week to change my battery charging mode.

What I don't get is how to use this?

I only find "at specific time", that doesn't work for me as I don't have a specific time to power on my PC.

Thanks! 🙏